name: temporal_graph_transformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch>=2.0.0
  - torchvision
  - numpy>=1.21.0
  - pandas>=1.4.0
  - scikit-learn>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - networkx>=2.8.0
  - tqdm>=4.64.0
  - pyyaml>=6.0
  - pip
  - pip:
    - torch-geometric>=2.3.0
    - transformers>=4.21.0
    - wandb>=0.13.0